package domain

import (
	"errors"
	"strings"
	"time"
)

var (
	ErrPaymentNotFound         = errors.New("payment not found")
	ErrInvalidAmount           = errors.New("amount must be greater than zero")
	ErrInvalidCurrency         = errors.New("currency must be a valid ISO 4217 code")
	ErrInvalidPaymentID        = errors.New("payment ID must be a valid UUID")
	ErrPaymentAlreadyCompleted = errors.New("payment has already been completed")
	ErrPaymentAlreadyProcessed = errors.New("payment has already been processed")
	ErrPaymentAlreadyFailed    = errors.New("payment has already failed")
	ErrPaymentAlreadyCancelled = errors.New("payment has already cancelled")
	ErrPaymentAlreadyRefunded  = errors.New("payment has already refunded")
	ErrClientBlacklisted       = errors.New("client is blacklisted, payment cannot be processed")
)

// PaymentStats is the lifecycle state of a payment.
type PaymentStats string

const (
	PaymentStatsPending   PaymentStats = "pending"
	PaymentStatsCompleted PaymentStats = "completed"
	PaymentStatsFailed    PaymentStats = "failed"
	PaymentStatsRefunded  PaymentStats = "refunded"
	PaymentStatsCancelled PaymentStats = "cancelled"
)

// Money is an amount expressed in the smallest minor unit of the currency
// (e.g. 100 = 1.00 THB, 100 = 1.00 USD, 1 JPY = 1). Integer arithmetic avoids
// the floating-point rounding errors that would corrupt financial records,
// matching how Stripe and Omise represent amounts in their APIs.
type Money int64

// IsValidCurrency reports whether s is a syntactically valid ISO 4217
// alphabetic code (3 uppercase letters). Actual support depends on the
// payment provider, so this only validates the format.
func IsValidCurrency(s string) bool {
	if len(s) != 3 {
		return false
	}
	for i := 0; i < len(s); i++ {
		c := s[i]
		if c < 'A' || c > 'Z' {
			return false
		}
	}
	return true
}

// Payment is the core domain aggregate. All state changes go through its
// methods so the aggregate can enforce its own invariants.
type Payment struct {
	ID            string       `json:"id"`
	UserID        string       `json:"user_id"`
	Amount        Money        `json:"amount"`
	Currency      string       `json:"currency"`
	Status        PaymentStats `json:"status"`
	ProviderTxnID string       `json:"provider_txn_id,omitempty"`
	CreatedAt     time.Time    `json:"created_at"`
}

// NewPayment creates a pending payment. The payment ID is generated by the
// caller (service layer); userID identifies the owner of the payment.
func NewPayment(id, userID string, amount Money, currency string) (*Payment, error) {
	if id == "" {
		return nil, ErrInvalidPaymentID
	}
	if amount <= 0 {
		return nil, ErrInvalidAmount
	}
	currency = strings.ToUpper(strings.TrimSpace(currency))
	if !IsValidCurrency(currency) {
		return nil, ErrInvalidCurrency
	}

	return &Payment{
		ID:        id,
		UserID:    userID,
		Amount:    amount,
		Currency:  currency,
		Status:    PaymentStatsPending,
		CreatedAt: time.Now(),
	}, nil
}

// Complete moves a pending payment to the completed state.
func (p *Payment) Complete() error {
	switch p.Status {
	case PaymentStatsPending:
		p.Status = PaymentStatsCompleted
		return nil
	case PaymentStatsCompleted:
		return ErrPaymentAlreadyCompleted
	case PaymentStatsFailed:
		return ErrPaymentAlreadyFailed
	case PaymentStatsCancelled:
		return ErrPaymentAlreadyCancelled
	case PaymentStatsRefunded:
		return ErrPaymentAlreadyRefunded
	default:
		return ErrPaymentAlreadyProcessed
	}
}

// Fail moves a pending payment to the failed state.
func (p *Payment) Fail() error {
	switch p.Status {
	case PaymentStatsPending:
		p.Status = PaymentStatsFailed
		return nil
	case PaymentStatsFailed:
		return ErrPaymentAlreadyFailed
	default:
		return ErrPaymentAlreadyProcessed
	}
}
